version: "3.9"

services:
  app:
    build: .
    container_name: app_node
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mysql
      - mongo
    volumes:
      - .:/app
    command: node server.js

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: s.a.m
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:7.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
  